### ISSUE TITLE
error TS2307: Cannot find module 'type-fest/source/simplify' or its corresponding type declarations

### ISSUE THREAD

**Issue by jugglingthebits** [contentful/contentful-management.js#931]
Updating to version 7.36.1 breaks our build with the following error

![grafik](https://user-images.githubusercontent.com/3235163/131813077-a479bbd2-a2fa-4efd-9a0d-dec3c66433f3.png)

`npm install type-fest --save-dev` appears to be a workaround, but shouldn't be needed.

**Comment by Dara-To** [comment]
I have the same issue with v7.29.0 and after update to 7.36.1. I am on my new iMac with M1 chip.

**Comment by tehpsy** [comment]
Is there any movement on this issue? It's stopping us from upgrading.

**Comment by iDVB** [comment]
Getting this issue also with `"contentful-management": "7.45.0",`

**Comment by slenzi** [comment]
Ditto, I am also seeing the issue with 7.45.0 (and confirmed that 7.36.0 works)
